# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_CAM_cpp <- function(nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, fixed_alpha, fixed_beta, alpha, beta, hyp_alpha1, hyp_alpha2, hyp_beta1, hyp_beta2, mu_start, sigma2_start, M_start, S_start, alpha_start, beta_start, progressbar) {
    .Call(`_SANple_sample_CAM_cpp`, nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, fixed_alpha, fixed_beta, alpha, beta, hyp_alpha1, hyp_alpha2, hyp_beta1, hyp_beta2, mu_start, sigma2_start, M_start, S_start, alpha_start, beta_start, progressbar)
}

sample_fiSAN_cpp <- function(nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, alpha, beta, hyp_alpha1, hyp_alpha2, fixed_alpha, mu_start, sigma2_start, M_start, S_start, progressbar) {
    .Call(`_SANple_sample_fiSAN_cpp`, nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, alpha, beta, hyp_alpha1, hyp_alpha2, fixed_alpha, mu_start, sigma2_start, M_start, S_start, progressbar)
}

sample_fSAN_cpp <- function(nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, alpha, beta, mu_start, sigma2_start, M_start, S_start, progressbar) {
    .Call(`_SANple_sample_fSAN_cpp`, nrep, burn, y, group, maxK, maxL, m0, tau0, lambda0, gamma0, alpha, beta, mu_start, sigma2_start, M_start, S_start, progressbar)
}

